In [2]:
import quandl

In [3]:
quandl.ApiConfig.api_key = "FDEDsMbK1E2t_PMf7X3M"

In [9]:
quandl.get('NSE/IBULISL')

,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
Date,,,,,,,
2018-06-08,561.00,561.00,531.00,542.00,539.20,22729.0,122.36
2018-06-11,515.00,548.00,512.25,525.00,524.85,60741.0,317.60
2018-06-12,498.70,534.00,498.70,525.00,525.05,38802.0,204.62
2018-06-13,515.00,545.00,515.00,540.00,540.50,34213.0,184.40
2018-06-14,545.00,564.95,541.50,545.00,549.25,49978.0,276.60
2018-06-15,555.00,555.00,525.05,530.00,528.60,13751.0,73.71
2018-06-18,511.10,533.00,502.20,504.90,503.45,29635.0,149.72
2018-06-19,504.00,504.00,478.30,478.30,478.95,59210.0,285.74
2018-06-20,478.30,502.85,465.00,502.85,502.85,70793.0,345.24
2018-06-21,524.00,527.95,515.00,527.95,527.95,32451.0,170.50
2018-06-22,546.00,550.00,511.25,525.00,530.90,68240.0,370.04
2018-06-25,530.90,538.00,504.55,514.95,511.15,29352.0,152.28
2018-06-26,506.00,520.00,496.00,500.10,500.40,26034.0,132.07
2018-06-27,500.00,508.30,476.25,482.00,484.95,41379.0,204.38
2018-06-28,462.20,498.65,462.20,466.00,470.80,30173.0,142.16
2018-06-29,471.00,494.30,469.00,480.45,485.90,38547.0,189.71
2018-07-02,503.90,503.90,461.65,465.00,464.60,34923.0,162.92
2018-07-03,460.00,474.00,450.10,455.00,460.25,25349.0,117.18
2018-07-04,450.20,459.00,437.25,455.00,451.40,48055.0,214.39
2018-07-05,469.80,469.80,429.15,431.00,435.50,31490.0,137.35
2018-07-06,420.00,457.25,415.05,450.00,450.85,31377.0,140.19
2018-07-09,460.10,473.00,453.00,470.00,471.05,28698.0,134.11
2018-07-10,475.00,477.00,460.00,463.00,463.95,12677.0,59.23
2018-07-11,450.10,460.00,444.00,447.00,449.45,9649.0,43.60
2018-07-12,449.45,465.50,441.00,453.45,447.75,9295.0,42.33
2018-07-13,440.00,463.90,436.00,441.00,438.10,15647.0,69.42
2018-07-16,433.30,448.00,417.20,417.20,422.85,27128.0,116.93
2018-07-17,422.85,439.90,401.75,432.00,428.10,39695.0,166.07
2018-07-18,427.00,449.50,416.00,425.00,427.80,77035.0,337.06
2018-07-19,420.00,432.00,416.10,428.75,424.35,32056.0,136.71
...,...,...,...,...,...,...,...
2018-10-31,320.00,344.55,320.00,344.55,344.55,238557.0,802.42
2018-11-01,355.00,361.75,342.25,348.55,349.90,384198.0,1382.19
2018-11-02,349.50,361.00,343.00,345.05,347.80,170245.0,602.98
2018-11-05,347.80,350.00,330.45,331.00,333.00,48057.0,161.00
2018-11-06,330.10,344.95,316.35,316.35,316.35,79016.0,255.82
2018-11-07,330.00,332.15,320.10,332.15,329.10,52244.0,172.35
2018-11-09,344.90,345.55,313.20,345.55,345.55,38498.0,132.34
2018-11-12,362.80,362.80,350.05,362.80,362.75,207542.0,751.29
2018-11-13,367.90,377.80,351.00,371.60,372.45,142006.0,526.47
2018-11-14,377.80,385.00,367.00,370.00,371.85,85933.0,323.36
2018-11-15,384.00,384.00,358.50,372.10,370.05,42674.0,156.30
2018-11-16,382.00,382.00,351.55,351.55,351.55,85515.0,311.03
2018-11-19,360.00,360.05,334.00,334.00,334.00,58603.0,196.37
2018-11-20,320.00,320.00,317.30,317.30,317.30,13748.0,43.63
2018-11-21,301.45,333.15,301.45,331.00,332.75,336997.0,1093.19
2018-11-22,332.00,340.00,316.15,316.15,318.60,87172.0,282.43
2018-11-26,315.00,321.00,302.70,302.70,304.20,67002.0,204.97
2018-11-27,301.45,301.75,289.00,293.00,293.20,98885.0,289.11
2018-11-28,287.20,296.20,278.55,278.55,278.55,158210.0,444.65
2018-11-29,279.95,292.45,270.00,292.45,292.45,30867.0,88.71
2018-11-30,307.05,307.05,302.00,307.05,307.05,133206.0,408.89
2018-12-03,322.20,322.40,310.00,311.30,312.55,109303.0,349.85
2018-12-04,315.00,328.15,303.65,313.90,310.35,130216.0,414.99
2018-12-05,295.00,310.00,294.85,294.85,294.85,62160.0,185.65
2018-12-06,292.00,293.00,280.15,280.15,280.25,82592.0,233.32
2018-12-07,281.10,289.00,266.25,272.65,268.60,44934.0,123.65
2018-12-10,256.20,265.00,255.20,255.20,255.20,116671.0,298.52
2018-12-11,242.50,267.95,242.45,267.95,267.95,323647.0,805.20
2018-12-12,269.90,281.30,267.95,281.30,281.30,20557.0,57.21
2018-12-13,295.35,295.35,295.35,295.35,295.35,4800.0,14.18

In [4]:
import pandas as pd

In [5]:
pd.read_csv("NSE_metadata.csv")

,code,name,description,refreshed_at,from_date,to_date
0,20MICRONS,20 Microns Limited,Historical prices for 20 Microns Limited<br><b...,2018-12-10 13:38:52,2008-10-06,2018-12-10
1,21STCENMGM,21st Century Management Services Limited,Historical prices for 21st Century Management ...,2018-12-10 13:38:52,2018-01-11,2018-12-10
2,3IINFOTECH,3i Infotech Limited,Historical prices for 3i Infotech Limited<br><...,2018-12-10 13:38:52,2005-04-22,2018-12-10
3,3MINDIA,3M India Limited,Historical prices for 3M India Limited<br><br>...,2018-12-10 13:38:52,2004-06-15,2018-12-10
4,3PLAND,3P Land Holdings Limited,Historical prices for 3P Land Holdings Limited...,2018-12-10 13:38:52,2018-05-04,2018-12-10
5,5PAISA,5Paisa Capital Limited,Historical prices for 5Paisa Capital Limited<b...,2018-12-10 13:38:52,2017-11-16,2018-12-10
6,63MOONS,63 moons technologies limited,Historical prices for 63 moons technologies li...,2018-12-10 13:38:52,2017-01-19,2018-12-10
7,8KMILES,8K Miles Software Services Limited,Historical prices for 8K Miles Software Servic...,2018-12-10 13:38:52,2014-01-29,2018-12-10
8,A2ZINFRA,A2Z Infra Engineering Limited,Historical prices for A2Z Infra Engineering Li...,2018-12-10 13:38:52,2014-12-31,2018-12-10
9,A2ZMES,A2Z Maintenance & Engineering Services Limited,Historical prices for A2Z Maintenance & Engine...,2015-03-09 09:30:10,2010-12-23,2014-12-30
10,AANJANEYA,Aanjaneya Lifecare Limited,Historical prices for Aanjaneya Lifecare Limit...,2013-11-28 16:18:32,2011-05-27,2013-08-30
11,AARTIDRUGS,Aarti Drugs Limited,Historical prices for Aarti Drugs Limited<br><...,2018-12-10 13:38:53,1998-03-19,2018-12-10
12,AARTIIND,Aarti Industries Limited,Historical prices for Aarti Industries Limited...,2018-12-10 13:38:53,1998-03-20,2018-12-10
13,AARVEEDEN,Aarvee Denims & Exports Limited,Historical prices for Aarvee Denims & Exports ...,2018-12-10 13:38:53,2006-11-21,2018-12-10
14,AAVAS,Aavas Financiers Limited,Historical prices for Aavas Financiers Limited...,2018-12-10 13:38:53,2018-10-08,2018-12-10
15,ABAN,Aban Offshore Limited,Historical prices for Aban Offshore Limited<br...,2018-12-10 13:38:53,2006-08-18,2018-12-10
16,ABB,ABB India Limited,Historical prices for ABB India Limited<br><br...,2018-12-10 13:38:53,1998-03-20,2018-12-10
17,ABBOTINDIA,Abbott India Limited,Historical prices for Abbott India Limited<br>...,2018-12-10 13:38:53,2010-01-08,2018-12-10
18,ABCAPITAL,Aditya Birla Capital Limited,Historical prices for Aditya Birla Capital Lim...,2018-12-10 13:38:53,2017-09-01,2018-12-10
19,ABCIL,Aditya Birla Chemicals (India) Limited,Historical prices for Aditya Birla Chemicals (...,2016-01-13 13:29:37,2009-03-09,2016-01-13
20,ABFRL,Aditya Birla Fashion and Retail Limited,Historical prices for Aditya Birla Fashion and...,2018-12-10 13:38:53,2016-01-29,2018-12-10
21,ABGSHIP,ABG Shipyard Limited,Historical prices for ABG Shipyard Limited<br>...,2018-12-10 13:38:53,2007-04-11,2018-12-10
22,ABHISHEK,Abhishek Corporation Limited,Historical prices for Abhishek Corporation Lim...,2013-08-27 12:39:20,2008-06-26,2013-04-05
23,ABIRLANUVO,Aditya Birla Nuvo Limited,Historical prices for Aditya Birla Nuvo Limite...,2017-07-04 13:19:26,2005-12-07,2017-07-04
24,ABMINTLTD,ABM International Limited,Historical prices for ABM International Limite...,2018-12-10 13:38:53,2017-01-30,2018-12-03
25,ACC,ACC Limited,Historical prices for ACC Limited<br><br>Natio...,2018-12-10 13:38:53,1998-03-20,2018-12-10
26,ACCELYA,Accelya Kale Solutions Limited,Historical prices for Accelya Kale Solutions L...,2018-12-10 13:38:53,2012-09-06,2018-12-10
27,ACE,Action Construction Equipment Limited,Historical prices for Action Construction Equi...,2018-12-10 13:38:53,2006-09-26,2018-12-10
28,ACKRUTI,Ackruti City Limited,Historical prices for Ackruti City Limited (AC...,2017-03-10 21:56:56,2009-06-30,2011-11-14
29,ACROPETAL,Acropetal Technologies Limited,Historical prices for Acropetal Technologies L...,2017-05-02 13:25:19,2011-03-10,2017-05-02
...,...,...,...,...,...,...
2225,WIPRO,Wipro Limited,Historical prices for Wipro Limited<br><br>Nat...,2018-12-10 13:39:07,1998-03-20,2018-12-10
2226,WOCKPHARMA,Wockhardt Limited,Historical prices for Wockhardt Limited<br><br...,2018-12-10 13:39:07,2000-02-23,2018-12-10
2227,WONDERLA,Wonderla Holidays Limited,Historical prices for Wonderla Holidays Limite...,2018-12-10 13:39:07,2014-05-09,2018-12-10
2228,WSI,W S Industries (I) Limited,Historical prices for W S Industries (I) Limit...,2018-12-10 13:39:07,2007-08-01,2018-12-07
2229,WSTCSTPAPR,West Coast Paper Mills Limited,Historical prices for West Coast Paper Mills L...,2018-12-10 13:39:07,1998-03-20,2018-12-10
2230,WWIL,Wire and Wireless (India) Limited,Historical prices for Wire and Wireless (India...,2014-03-31 16:31:38,2007-01-10,2012-10-01
2231,WYETH,Wyeth Limited,"Historical prices for Wyeth Limited (WYETH), (...",2015-03-09 09:18:14,2006-09-01,2014-12-09
2232,XCHANGING,Xchanging Solutions Limited,Historical prices for Xchanging Solutions Limi...,2018-12-10 13:39:07,2012-06-25,2018-12-10
2233,XLENERGY,XL Energy Limited,Historical prices for XL Energy Limited<br><br...,2018-12-10 13:39:07,2010-12-13,2018-12-10
2234,XPROINDIA,Xpro India Limited,Historical prices for Xpro India Limited<br><b...,2018-12-10 13:39:07,2004-04-27,2018-12-10
2235,YESBANK,Yes Bank Limited,Historical prices for Yes Bank Limited<br><br>...,2018-12-10 13:39:07,2005-07-12,2018-12-10
2236,ZANDUREALT,Zandu Realty Limited,Historical prices for Zandu Realty Limited<br>...,2018-05-23 13:28:05,2010-03-10,2018-05-23
2237,ZEEL,Zee Entertainment Enterprises Limited,Historical prices for Zee Entertainment Enterp...,2018-12-10 13:39:07,2007-02-28,2018-12-10
2238,ZEELEARN,Zee Learn Limited,Historical prices for Zee Learn Limited<br><br...,2018-12-10 13:39:07,2010-12-20,2018-12-10
2239,ZEEMEDIA,Zee Media Corporation Limited,Historical prices for Zee Media Corporation Li...,2018-12-10 13:39:07,2013-07-30,2018-12-10
2240,ZEENEWS,Zee News Limited,Historical prices for Zee News Limited (ZEENEW...,2013-10-27 16:35:31,2007-01-10,2013-07-29
2241,ZENITHBIR,Zenith Birla (India) Limited,Historical prices for Zenith Birla (India) Lim...,2018-12-10 13:39:07,2007-04-30,2018-12-10
2242,ZENITHCOMP,Zenith Computers Limited,Historical prices for Zenith Computers Limited...,2016-01-11 13:38:19,2000-05-10,2016-01-11
2243,ZENITHEXPO,Zenith Exports Limited,Historical prices for Zenith Exports Limited<b...,2018-12-10 13:39:07,1998-03-12,2018-12-07
2244,ZENITHINFO,Zenith Infotech Limited,Historical prices for Zenith Infotech Limited ...,2014-06-30 23:04:49,2000-02-14,2013-07-05
2245,ZENSARTECH,Zensar Technologies Limited,Historical prices for Zensar Technologies Limi...,2018-12-10 13:39:07,2004-03-04,2018-12-10
2246,ZENTEC,Zen Technologies Limited,Historical prices for Zen Technologies Limited...,2018-12-10 13:39:07,2015-03-30,2018-12-10
2247,ZICOM,Zicom Electronic Security Systems Limited,Historical prices for Zicom Electronic Securit...,2018-12-10 13:39:07,2006-04-18,2018-12-10
2248,ZODIACLOTH,Zodiac Clothing Company Limited,Historical prices for Zodiac Clothing Company ...,2018-12-10 13:39:07,1998-03-17,2018-12-10
2249,ZODJRDMKJ,Zodiac JRD- MKJ Limited,Historical prices for Zodiac JRD- MKJ Limited<...,2018-12-10 13:39:07,1998-03-20,2018-12-10
2250,ZUARI,Zuari Agro Chemicals Limited,Historical prices for Zuari Agro Chemicals Lim...,2018-12-10 13:39:07,2012-11-27,2018-12-10
2251,ZUARIAGRO,Zuari Industries Limited,Historical prices for Zuari Industries Limited...,2014-03-31 18:14:00,1998-03-20,2012-09-24
2252,ZUARIGLOB,Zuari Global Limited,Historical prices for Zuari Global Limited<br>...,2018-12-10 13:39:07,2012-09-25,2018-12-10
2253,ZYDUSWELL,Zydus Wellness Limited,Historical prices for Zydus Wellness Limited<b...,2018-12-10 13:39:07,2009-11-13,2018-12-10
2254,ZYLOG,Zylog Systems Limited,Historical prices for Zylog Systems Limited<br...,2018-12-10 13:39:07,2007-08-17,2018-12-10